import localFont from "next/font/local";
import ReduxProvider from '@/store/reduxProvider';
import "./globals.css";

const mulish = localFont({
  src: "./fonts/Mulish.woff",
  variable: "--font-mulish-sans",
});
const cormorant = localFont({
  src: "./fonts/Cormorant.woff",
  variable: "--font-cormorant-sans",
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body
          className={`${mulish.variable} ${cormorant.variable} antialiased`}
        >
          {children}
        </body>
      </html>
    </ReduxProvider>
  );
}
